# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'GUIDocente.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.setEnabled(True)
        Form.resize(681, 400)
        Form.setMinimumSize(QtCore.QSize(681, 400))
        Form.setAutoFillBackground(False)
        Form.setStyleSheet("background-color: rgb(223, 223, 223);")
        self.tabWidget = QtWidgets.QTabWidget(Form)
        self.tabWidget.setEnabled(True)
        self.tabWidget.setGeometry(QtCore.QRect(0, 0, 741, 400))
        self.tabWidget.setMinimumSize(QtCore.QSize(681, 400))
        self.tabWidget.setStyleSheet("background-color: rgb(223, 223, 223);\n"
"selection-color: rgb(0, 0, 0);\n"
"color: rgb(0, 0, 0);\n"
"selection-background-color: rgb(255, 255, 255);\n"
"alternate-background-color: rgb(255, 255, 255);")
        self.tabWidget.setObjectName("tabWidget")
        self.tab_1 = QtWidgets.QWidget()
        self.tab_1.setObjectName("tab_1")
        self.bt_refrescar = QtWidgets.QPushButton(self.tab_1)
        self.bt_refrescar.setGeometry(QtCore.QRect(500, 160, 91, 31))
        self.bt_refrescar.setStyleSheet("background-color: rgb(85, 0, 255);\n"
"color: rgb(255, 255, 255);\n"
"font: 75 10pt \"MS Shell Dlg 2\";")
        self.bt_refrescar.setObjectName("bt_refrescar")
        self.tabla_docentes = QtWidgets.QTableWidget(self.tab_1)
        self.tabla_docentes.setGeometry(QtCore.QRect(30, 20, 401, 331))
        self.tabla_docentes.setRowCount(0)
        self.tabla_docentes.setColumnCount(4)
        self.tabla_docentes.setObjectName("tabla_docentes")
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        item.setBackground(QtGui.QColor(255, 0, 191))
        self.tabla_docentes.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        item.setBackground(QtGui.QColor(85, 255, 127))
        self.tabla_docentes.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        item.setBackground(QtGui.QColor(255, 248, 53))
        self.tabla_docentes.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        font.setStyleStrategy(QtGui.QFont.PreferDefault)
        item.setFont(font)
        self.tabla_docentes.setHorizontalHeaderItem(3, item)
        self.tabWidget.addTab(self.tab_1, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.bt_agregar = QtWidgets.QPushButton(self.tab_2)
        self.bt_agregar.setGeometry(QtCore.QRect(270, 270, 75, 23))
        self.bt_agregar.setStyleSheet("background-color: rgb(85, 0, 255);\n"
"color: rgb(255, 255, 255);\n"
"font: 75 10pt \"MS Shell Dlg 2\";")
        self.bt_agregar.setObjectName("bt_agregar")
        self.layoutWidget_3 = QtWidgets.QWidget(self.tab_2)
        self.layoutWidget_3.setGeometry(QtCore.QRect(200, 30, 241, 211))
        self.layoutWidget_3.setObjectName("layoutWidget_3")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.layoutWidget_3)
        self.horizontalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout()
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.label_9 = QtWidgets.QLabel(self.layoutWidget_3)
        self.label_9.setObjectName("label_9")
        self.verticalLayout_5.addWidget(self.label_9)
        self.label_10 = QtWidgets.QLabel(self.layoutWidget_3)
        self.label_10.setObjectName("label_10")
        self.verticalLayout_5.addWidget(self.label_10)
        self.label_11 = QtWidgets.QLabel(self.layoutWidget_3)
        self.label_11.setObjectName("label_11")
        self.verticalLayout_5.addWidget(self.label_11)
        self.label_12 = QtWidgets.QLabel(self.layoutWidget_3)
        self.label_12.setObjectName("label_12")
        self.verticalLayout_5.addWidget(self.label_12)
        self.horizontalLayout_3.addLayout(self.verticalLayout_5)
        self.verticalLayout_6 = QtWidgets.QVBoxLayout()
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.idA = QtWidgets.QLineEdit(self.layoutWidget_3)
        self.idA.setObjectName("idA")
        self.verticalLayout_6.addWidget(self.idA)
        self.tercernivelA = QtWidgets.QLineEdit(self.layoutWidget_3)
        self.tercernivelA.setObjectName("tercernivelA")
        self.verticalLayout_6.addWidget(self.tercernivelA)
        self.cuartonivelA = QtWidgets.QLineEdit(self.layoutWidget_3)
        self.cuartonivelA.setObjectName("cuartonivelA")
        self.verticalLayout_6.addWidget(self.cuartonivelA)
        self.contador_docenteA = QtWidgets.QLineEdit(self.layoutWidget_3)
        self.contador_docenteA.setObjectName("contador_docenteA")
        self.verticalLayout_6.addWidget(self.contador_docenteA)
        self.horizontalLayout_3.addLayout(self.verticalLayout_6)
        self.tabWidget.addTab(self.tab_2, "")
        self.tab_3 = QtWidgets.QWidget()
        self.tab_3.setObjectName("tab_3")
        self.bt_actualizar = QtWidgets.QPushButton(self.tab_3)
        self.bt_actualizar.setGeometry(QtCore.QRect(380, 290, 91, 21))
        self.bt_actualizar.setStyleSheet("background-color: rgb(85, 0, 255);\n"
"color: rgb(255, 255, 255);\n"
"font: 75 10pt \"MS Shell Dlg 2\";")
        self.bt_actualizar.setObjectName("bt_actualizar")
        self.id_estudiante = QtWidgets.QLineEdit(self.tab_3)
        self.id_estudiante.setGeometry(QtCore.QRect(50, 140, 180, 20))
        self.id_estudiante.setObjectName("id_estudiante")
        self.label_13 = QtWidgets.QLabel(self.tab_3)
        self.label_13.setGeometry(QtCore.QRect(80, 90, 131, 39))
        self.label_13.setObjectName("label_13")
        self.id_buscar = QtWidgets.QPushButton(self.tab_3)
        self.id_buscar.setGeometry(QtCore.QRect(100, 180, 75, 23))
        self.id_buscar.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.id_buscar.setObjectName("id_buscar")
        self.layoutWidget_2 = QtWidgets.QWidget(self.tab_3)
        self.layoutWidget_2.setGeometry(QtCore.QRect(320, 40, 241, 211))
        self.layoutWidget_2.setObjectName("layoutWidget_2")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.layoutWidget_2)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.label_5 = QtWidgets.QLabel(self.layoutWidget_2)
        self.label_5.setObjectName("label_5")
        self.verticalLayout_3.addWidget(self.label_5)
        self.label_6 = QtWidgets.QLabel(self.layoutWidget_2)
        self.label_6.setObjectName("label_6")
        self.verticalLayout_3.addWidget(self.label_6)
        self.label_7 = QtWidgets.QLabel(self.layoutWidget_2)
        self.label_7.setObjectName("label_7")
        self.verticalLayout_3.addWidget(self.label_7)
        self.label_8 = QtWidgets.QLabel(self.layoutWidget_2)
        self.label_8.setObjectName("label_8")
        self.verticalLayout_3.addWidget(self.label_8)
        self.horizontalLayout_2.addLayout(self.verticalLayout_3)
        self.verticalLayout_4 = QtWidgets.QVBoxLayout()
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.id_actualizar = QtWidgets.QLineEdit(self.layoutWidget_2)
        self.id_actualizar.setObjectName("id_actualizar")
        self.verticalLayout_4.addWidget(self.id_actualizar)
        self.tercernivel_actualizar = QtWidgets.QLineEdit(self.layoutWidget_2)
        self.tercernivel_actualizar.setObjectName("tercernivel_actualizar")
        self.verticalLayout_4.addWidget(self.tercernivel_actualizar)
        self.cuartonivel_actualizar = QtWidgets.QLineEdit(self.layoutWidget_2)
        self.cuartonivel_actualizar.setObjectName("cuartonivel_actualizar")
        self.verticalLayout_4.addWidget(self.cuartonivel_actualizar)
        self.contador_docente_actualizar = QtWidgets.QLineEdit(self.layoutWidget_2)
        self.contador_docente_actualizar.setObjectName("contador_docente_actualizar")
        self.verticalLayout_4.addWidget(self.contador_docente_actualizar)
        self.horizontalLayout_2.addLayout(self.verticalLayout_4)
        self.tabWidget.addTab(self.tab_3, "")
        self.tab_4 = QtWidgets.QWidget()
        self.tab_4.setObjectName("tab_4")
        self.borrar_ok = QtWidgets.QPushButton(self.tab_4)
        self.borrar_ok.setGeometry(QtCore.QRect(500, 170, 91, 23))
        self.borrar_ok.setStyleSheet("background-color: rgb(255, 0, 127);")
        self.borrar_ok.setObjectName("borrar_ok")
        self.label_18 = QtWidgets.QLabel(self.tab_4)
        self.label_18.setGeometry(QtCore.QRect(430, 80, 31, 16))
        self.label_18.setObjectName("label_18")
        self.id_borrar = QtWidgets.QLineEdit(self.tab_4)
        self.id_borrar.setGeometry(QtCore.QRect(460, 80, 101, 20))
        self.id_borrar.setText("")
        self.id_borrar.setObjectName("id_borrar")
        self.bt_borrar = QtWidgets.QPushButton(self.tab_4)
        self.bt_borrar.setGeometry(QtCore.QRect(580, 80, 75, 23))
        self.bt_borrar.setStyleSheet("background-color: rgb(85, 0, 255);\n"
"color: rgb(255, 255, 255);\n"
"font: 75 10pt \"MS Shell Dlg 2\";")
        self.bt_borrar.setObjectName("bt_borrar")
        self.tabla_borrar = QtWidgets.QTableWidget(self.tab_4)
        self.tabla_borrar.setGeometry(QtCore.QRect(10, 30, 401, 331))
        self.tabla_borrar.setRowCount(0)
        self.tabla_borrar.setColumnCount(4)
        self.tabla_borrar.setObjectName("tabla_borrar")
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        item.setBackground(QtGui.QColor(255, 0, 191))
        self.tabla_borrar.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        item.setBackground(QtGui.QColor(85, 255, 127))
        self.tabla_borrar.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        item.setBackground(QtGui.QColor(255, 248, 53))
        self.tabla_borrar.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        font.setStyleStrategy(QtGui.QFont.PreferDefault)
        item.setFont(font)
        self.tabla_borrar.setHorizontalHeaderItem(3, item)
        self.tabWidget.addTab(self.tab_4, "")

        self.retranslateUi(Form)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "REGISTRO DE DOCENTES"))
        self.bt_refrescar.setText(_translate("Form", "REFRESCAR"))
        item = self.tabla_docentes.horizontalHeaderItem(0)
        item.setText(_translate("Form", "Id"))
        item = self.tabla_docentes.horizontalHeaderItem(1)
        item.setText(_translate("Form", "Titulo 3er Nivel"))
        item = self.tabla_docentes.horizontalHeaderItem(2)
        item.setText(_translate("Form", "Titulo 4to Nivel"))
        item = self.tabla_docentes.horizontalHeaderItem(3)
        item.setText(_translate("Form", "Contador Docente"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_1), _translate("Form", "DOCENTES"))
        self.bt_agregar.setText(_translate("Form", "AGREGAR"))
        self.label_9.setText(_translate("Form", "ID:"))
        self.label_10.setText(_translate("Form", "TITULO 3ER NIVEL:"))
        self.label_11.setText(_translate("Form", "TITULO 3ER NIVEL:"))
        self.label_12.setText(_translate("Form", "CONTADOR DOCENTE:"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("Form", "AGREGAR NUEVOS DOCENTES"))
        self.bt_actualizar.setText(_translate("Form", "ACTUALIZAR"))
        self.label_13.setText(_translate("Form", "INGRESE EL ID DEL LIBRO"))
        self.id_buscar.setText(_translate("Form", "BUSCAR"))
        self.label_5.setText(_translate("Form", "ID:"))
        self.label_6.setText(_translate("Form", "TITULO 3ER NIVEL:"))
        self.label_7.setText(_translate("Form", "TITULO 3ER NIVEL:"))
        self.label_8.setText(_translate("Form", "CONTADOR DOCENTE:"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_3), _translate("Form", "ACTUALIZAR DOCENTES"))
        self.borrar_ok.setText(_translate("Form", "Consultar"))
        self.label_18.setText(_translate("Form", "ID:"))
        self.bt_borrar.setText(_translate("Form", "BORRAR"))
        item = self.tabla_borrar.horizontalHeaderItem(0)
        item.setText(_translate("Form", "Id"))
        item = self.tabla_borrar.horizontalHeaderItem(1)
        item.setText(_translate("Form", "Titulo 3er Nivel"))
        item = self.tabla_borrar.horizontalHeaderItem(2)
        item.setText(_translate("Form", "Titulo 4to Nivel"))
        item = self.tabla_borrar.horizontalHeaderItem(3)
        item.setText(_translate("Form", "Contador Docente"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_4), _translate("Form", "BORRAR DOCENTES"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())

