# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'GUILibro.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.setEnabled(True)
        Form.resize(681, 400)
        Form.setMinimumSize(QtCore.QSize(681, 400))
        Form.setAutoFillBackground(False)
        Form.setStyleSheet("background-color: rgb(223, 223, 223);")
        self.tabWidget = QtWidgets.QTabWidget(Form)
        self.tabWidget.setEnabled(True)
        self.tabWidget.setGeometry(QtCore.QRect(0, 0, 741, 400))
        self.tabWidget.setMinimumSize(QtCore.QSize(681, 400))
        self.tabWidget.setStyleSheet("background-color: rgb(223, 223, 223);\n"
"selection-color: rgb(0, 0, 0);\n"
"color: rgb(0, 0, 0);\n"
"selection-background-color: rgb(255, 255, 255);\n"
"alternate-background-color: rgb(255, 255, 255);")
        self.tabWidget.setObjectName("tabWidget")
        self.tab_1 = QtWidgets.QWidget()
        self.tab_1.setObjectName("tab_1")
        self.bt_refrescar = QtWidgets.QPushButton(self.tab_1)
        self.bt_refrescar.setGeometry(QtCore.QRect(440, 160, 91, 31))
        self.bt_refrescar.setStyleSheet("background-color: rgb(85, 0, 255);\n"
"color: rgb(255, 255, 255);\n"
"font: 75 10pt \"MS Shell Dlg 2\";")
        self.bt_refrescar.setObjectName("bt_refrescar")
        self.tabla_libros = QtWidgets.QTableWidget(self.tab_1)
        self.tabla_libros.setGeometry(QtCore.QRect(30, 20, 301, 331))
        self.tabla_libros.setRowCount(0)
        self.tabla_libros.setColumnCount(3)
        self.tabla_libros.setObjectName("tabla_libros")
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        item.setBackground(QtGui.QColor(255, 0, 191))
        self.tabla_libros.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        item.setBackground(QtGui.QColor(85, 255, 127))
        self.tabla_libros.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        item.setBackground(QtGui.QColor(255, 248, 53))
        self.tabla_libros.setHorizontalHeaderItem(2, item)
        self.tabWidget.addTab(self.tab_1, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.bt_agregar = QtWidgets.QPushButton(self.tab_2)
        self.bt_agregar.setGeometry(QtCore.QRect(270, 270, 75, 23))
        self.bt_agregar.setStyleSheet("background-color: rgb(85, 0, 255);\n"
"color: rgb(255, 255, 255);\n"
"font: 75 10pt \"MS Shell Dlg 2\";")
        self.bt_agregar.setObjectName("bt_agregar")
        self.layoutWidget = QtWidgets.QWidget(self.tab_2)
        self.layoutWidget.setGeometry(QtCore.QRect(190, 30, 241, 211))
        self.layoutWidget.setObjectName("layoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.layoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label_2 = QtWidgets.QLabel(self.layoutWidget)
        self.label_2.setObjectName("label_2")
        self.verticalLayout_2.addWidget(self.label_2)
        self.label_3 = QtWidgets.QLabel(self.layoutWidget)
        self.label_3.setObjectName("label_3")
        self.verticalLayout_2.addWidget(self.label_3)
        self.label_4 = QtWidgets.QLabel(self.layoutWidget)
        self.label_4.setObjectName("label_4")
        self.verticalLayout_2.addWidget(self.label_4)
        self.horizontalLayout.addLayout(self.verticalLayout_2)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.idA = QtWidgets.QLineEdit(self.layoutWidget)
        self.idA.setObjectName("idA")
        self.verticalLayout.addWidget(self.idA)
        self.tipo_pastaA = QtWidgets.QLineEdit(self.layoutWidget)
        self.tipo_pastaA.setObjectName("tipo_pastaA")
        self.verticalLayout.addWidget(self.tipo_pastaA)
        self.contador_libroA = QtWidgets.QLineEdit(self.layoutWidget)
        self.contador_libroA.setObjectName("contador_libroA")
        self.verticalLayout.addWidget(self.contador_libroA)
        self.horizontalLayout.addLayout(self.verticalLayout)
        self.tabWidget.addTab(self.tab_2, "")
        self.tab_3 = QtWidgets.QWidget()
        self.tab_3.setObjectName("tab_3")
        self.bt_actualizar = QtWidgets.QPushButton(self.tab_3)
        self.bt_actualizar.setGeometry(QtCore.QRect(380, 290, 91, 21))
        self.bt_actualizar.setStyleSheet("background-color: rgb(85, 0, 255);\n"
"color: rgb(255, 255, 255);\n"
"font: 75 10pt \"MS Shell Dlg 2\";")
        self.bt_actualizar.setObjectName("bt_actualizar")
        self.id_libro = QtWidgets.QLineEdit(self.tab_3)
        self.id_libro.setGeometry(QtCore.QRect(30, 120, 180, 20))
        self.id_libro.setObjectName("id_libro")
        self.label_13 = QtWidgets.QLabel(self.tab_3)
        self.label_13.setGeometry(QtCore.QRect(30, 70, 191, 39))
        self.label_13.setObjectName("label_13")
        self.id_buscar = QtWidgets.QPushButton(self.tab_3)
        self.id_buscar.setGeometry(QtCore.QRect(70, 150, 75, 23))
        self.id_buscar.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.id_buscar.setObjectName("id_buscar")
        self.layoutWidget_2 = QtWidgets.QWidget(self.tab_3)
        self.layoutWidget_2.setGeometry(QtCore.QRect(310, 40, 241, 211))
        self.layoutWidget_2.setObjectName("layoutWidget_2")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.layoutWidget_2)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.label_5 = QtWidgets.QLabel(self.layoutWidget_2)
        self.label_5.setObjectName("label_5")
        self.verticalLayout_3.addWidget(self.label_5)
        self.label_6 = QtWidgets.QLabel(self.layoutWidget_2)
        self.label_6.setObjectName("label_6")
        self.verticalLayout_3.addWidget(self.label_6)
        self.label_7 = QtWidgets.QLabel(self.layoutWidget_2)
        self.label_7.setObjectName("label_7")
        self.verticalLayout_3.addWidget(self.label_7)
        self.horizontalLayout_2.addLayout(self.verticalLayout_3)
        self.verticalLayout_4 = QtWidgets.QVBoxLayout()
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.id_actualizar = QtWidgets.QLineEdit(self.layoutWidget_2)
        self.id_actualizar.setObjectName("id_actualizar")
        self.verticalLayout_4.addWidget(self.id_actualizar)
        self.tipo_pasta_actualizar = QtWidgets.QLineEdit(self.layoutWidget_2)
        self.tipo_pasta_actualizar.setObjectName("tipo_pasta_actualizar")
        self.verticalLayout_4.addWidget(self.tipo_pasta_actualizar)
        self.contador_libro_actualizar = QtWidgets.QLineEdit(self.layoutWidget_2)
        self.contador_libro_actualizar.setObjectName("contador_libro_actualizar")
        self.verticalLayout_4.addWidget(self.contador_libro_actualizar)
        self.horizontalLayout_2.addLayout(self.verticalLayout_4)
        self.tabWidget.addTab(self.tab_3, "")
        self.tab_4 = QtWidgets.QWidget()
        self.tab_4.setObjectName("tab_4")
        self.borrar_ok = QtWidgets.QPushButton(self.tab_4)
        self.borrar_ok.setGeometry(QtCore.QRect(440, 190, 91, 23))
        self.borrar_ok.setStyleSheet("background-color: rgb(255, 0, 127);")
        self.borrar_ok.setObjectName("borrar_ok")
        self.label_18 = QtWidgets.QLabel(self.tab_4)
        self.label_18.setGeometry(QtCore.QRect(370, 130, 45, 16))
        self.label_18.setObjectName("label_18")
        self.id_borrar = QtWidgets.QLineEdit(self.tab_4)
        self.id_borrar.setGeometry(QtCore.QRect(421, 130, 101, 20))
        self.id_borrar.setText("")
        self.id_borrar.setObjectName("id_borrar")
        self.bt_borrar = QtWidgets.QPushButton(self.tab_4)
        self.bt_borrar.setGeometry(QtCore.QRect(540, 130, 75, 23))
        self.bt_borrar.setStyleSheet("background-color: rgb(85, 0, 255);\n"
"color: rgb(255, 255, 255);\n"
"font: 75 10pt \"MS Shell Dlg 2\";")
        self.bt_borrar.setObjectName("bt_borrar")
        self.tabla_borrar = QtWidgets.QTableWidget(self.tab_4)
        self.tabla_borrar.setGeometry(QtCore.QRect(30, 20, 301, 331))
        self.tabla_borrar.setRowCount(0)
        self.tabla_borrar.setColumnCount(3)
        self.tabla_borrar.setObjectName("tabla_borrar")
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        item.setBackground(QtGui.QColor(255, 0, 191))
        self.tabla_borrar.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        item.setBackground(QtGui.QColor(85, 255, 127))
        self.tabla_borrar.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        item.setBackground(QtGui.QColor(255, 248, 53))
        self.tabla_borrar.setHorizontalHeaderItem(2, item)
        self.tabWidget.addTab(self.tab_4, "")

        self.retranslateUi(Form)
        self.tabWidget.setCurrentIndex(2)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "REGISTRO DE LIBROS"))
        self.bt_refrescar.setText(_translate("Form", "REFRESCAR"))
        item = self.tabla_libros.horizontalHeaderItem(0)
        item.setText(_translate("Form", "Id"))
        item = self.tabla_libros.horizontalHeaderItem(1)
        item.setText(_translate("Form", "Tipo Pasta"))
        item = self.tabla_libros.horizontalHeaderItem(2)
        item.setText(_translate("Form", "Contador Libro"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_1), _translate("Form", "LIBROS"))
        self.bt_agregar.setText(_translate("Form", "AGREGAR"))
        self.label_2.setText(_translate("Form", "ID:"))
        self.label_3.setText(_translate("Form", "TIPO PASTA"))
        self.label_4.setText(_translate("Form", "CONTADOR LIBRO"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("Form", "AGREGAR NUEVOS LIBROS"))
        self.bt_actualizar.setText(_translate("Form", "ACTUALIZAR"))
        self.label_13.setText(_translate("Form", "INGRESE EL ID DEL LIBRO"))
        self.id_buscar.setText(_translate("Form", "BUSCAR"))
        self.label_5.setText(_translate("Form", "ID:"))
        self.label_6.setText(_translate("Form", "TIPO PASTA"))
        self.label_7.setText(_translate("Form", "CONTADOR LIBRO"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_3), _translate("Form", "ACTUALIZAR LIBROS"))
        self.borrar_ok.setText(_translate("Form", "Consultar"))
        self.label_18.setText(_translate("Form", "ID:"))
        self.bt_borrar.setText(_translate("Form", "BORRAR"))
        item = self.tabla_borrar.horizontalHeaderItem(0)
        item.setText(_translate("Form", "Id"))
        item = self.tabla_borrar.horizontalHeaderItem(1)
        item.setText(_translate("Form", "Tipo Pasta"))
        item = self.tabla_borrar.horizontalHeaderItem(2)
        item.setText(_translate("Form", "Contador Libro"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_4), _translate("Form", "BORRAR LIBROS"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())

