# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'GUIMaterial.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.setEnabled(True)
        Form.resize(745, 400)
        Form.setMinimumSize(QtCore.QSize(681, 400))
        Form.setStyleSheet("background-color: rgb(223, 223, 223);\n"
"selection-color: rgb(0, 0, 0);\n"
"color: rgb(0, 0, 0);\n"
"selection-background-color: rgb(255, 255, 255);\n"
"alternate-background-color: rgb(255, 255, 255);")
        self.pantalla = QtWidgets.QTabWidget(Form)
        self.pantalla.setEnabled(True)
        self.pantalla.setGeometry(QtCore.QRect(0, 0, 751, 400))
        self.pantalla.setMinimumSize(QtCore.QSize(681, 400))
        self.pantalla.setStyleSheet("")
        self.pantalla.setObjectName("pantalla")
        self.tab_5 = QtWidgets.QWidget()
        self.tab_5.setObjectName("tab_5")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.tab_5)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.tabla_materiales = QtWidgets.QTableWidget(self.tab_5)
        self.tabla_materiales.setRowCount(0)
        self.tabla_materiales.setColumnCount(8)
        self.tabla_materiales.setObjectName("tabla_materiales")
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        item.setBackground(QtGui.QColor(255, 0, 191))
        self.tabla_materiales.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        item.setBackground(QtGui.QColor(85, 255, 127))
        self.tabla_materiales.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        item.setBackground(QtGui.QColor(255, 248, 53))
        self.tabla_materiales.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        item.setBackground(QtGui.QColor(0, 170, 127))
        self.tabla_materiales.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        item.setBackground(QtGui.QColor(255, 170, 0))
        self.tabla_materiales.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        item.setBackground(QtGui.QColor(0, 85, 255))
        self.tabla_materiales.setHorizontalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        item.setBackground(QtGui.QColor(163, 83, 26))
        self.tabla_materiales.setHorizontalHeaderItem(6, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        item.setBackground(QtGui.QColor(0, 170, 127))
        self.tabla_materiales.setHorizontalHeaderItem(7, item)
        self.horizontalLayout_3.addWidget(self.tabla_materiales)
        self.bt_refrescar = QtWidgets.QPushButton(self.tab_5)
        self.bt_refrescar.setStyleSheet("background-color: rgb(85, 0, 255);\n"
"color: rgb(255, 255, 255);\n"
"font: 75 10pt \"MS Shell Dlg 2\";")
        self.bt_refrescar.setObjectName("bt_refrescar")
        self.horizontalLayout_3.addWidget(self.bt_refrescar)
        self.pantalla.addTab(self.tab_5, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.bt_agregar = QtWidgets.QPushButton(self.tab_2)
        self.bt_agregar.setGeometry(QtCore.QRect(320, 290, 75, 23))
        self.bt_agregar.setStyleSheet("background-color: rgb(85, 0, 255);\n"
"color: rgb(255, 255, 255);\n"
"font: 75 10pt \"MS Shell Dlg 2\";")
        self.bt_agregar.setObjectName("bt_agregar")
        self.layoutWidget = QtWidgets.QWidget(self.tab_2)
        self.layoutWidget.setGeometry(QtCore.QRect(70, 50, 241, 211))
        self.layoutWidget.setObjectName("layoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.layoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label_2 = QtWidgets.QLabel(self.layoutWidget)
        self.label_2.setObjectName("label_2")
        self.verticalLayout_2.addWidget(self.label_2)
        self.label_3 = QtWidgets.QLabel(self.layoutWidget)
        self.label_3.setObjectName("label_3")
        self.verticalLayout_2.addWidget(self.label_3)
        self.label_4 = QtWidgets.QLabel(self.layoutWidget)
        self.label_4.setObjectName("label_4")
        self.verticalLayout_2.addWidget(self.label_4)
        self.label_5 = QtWidgets.QLabel(self.layoutWidget)
        self.label_5.setObjectName("label_5")
        self.verticalLayout_2.addWidget(self.label_5)
        self.label_6 = QtWidgets.QLabel(self.layoutWidget)
        self.label_6.setObjectName("label_6")
        self.verticalLayout_2.addWidget(self.label_6)
        self.horizontalLayout.addLayout(self.verticalLayout_2)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.codigoA = QtWidgets.QLineEdit(self.layoutWidget)
        self.codigoA.setObjectName("codigoA")
        self.verticalLayout.addWidget(self.codigoA)
        self.autorA = QtWidgets.QLineEdit(self.layoutWidget)
        self.autorA.setObjectName("autorA")
        self.verticalLayout.addWidget(self.autorA)
        self.tituloA = QtWidgets.QLineEdit(self.layoutWidget)
        self.tituloA.setObjectName("tituloA")
        self.verticalLayout.addWidget(self.tituloA)
        self.anioA = QtWidgets.QLineEdit(self.layoutWidget)
        self.anioA.setObjectName("anioA")
        self.verticalLayout.addWidget(self.anioA)
        self.editorialA = QtWidgets.QLineEdit(self.layoutWidget)
        self.editorialA.setObjectName("editorialA")
        self.verticalLayout.addWidget(self.editorialA)
        self.horizontalLayout.addLayout(self.verticalLayout)
        self.layoutWidget_2 = QtWidgets.QWidget(self.tab_2)
        self.layoutWidget_2.setGeometry(QtCore.QRect(380, 50, 231, 211))
        self.layoutWidget_2.setObjectName("layoutWidget_2")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.layoutWidget_2)
        self.horizontalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout()
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.label_14 = QtWidgets.QLabel(self.layoutWidget_2)
        self.label_14.setObjectName("label_14")
        self.verticalLayout_5.addWidget(self.label_14)
        self.label_16 = QtWidgets.QLabel(self.layoutWidget_2)
        self.label_16.setObjectName("label_16")
        self.verticalLayout_5.addWidget(self.label_16)
        self.label_17 = QtWidgets.QLabel(self.layoutWidget_2)
        self.label_17.setObjectName("label_17")
        self.verticalLayout_5.addWidget(self.label_17)
        self.horizontalLayout_4.addLayout(self.verticalLayout_5)
        self.verticalLayout_6 = QtWidgets.QVBoxLayout()
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.disponibleA = QtWidgets.QLineEdit(self.layoutWidget_2)
        self.disponibleA.setObjectName("disponibleA")
        self.verticalLayout_6.addWidget(self.disponibleA)
        self.cantidad_disponibleA = QtWidgets.QLineEdit(self.layoutWidget_2)
        self.cantidad_disponibleA.setObjectName("cantidad_disponibleA")
        self.verticalLayout_6.addWidget(self.cantidad_disponibleA)
        self.ntipoA = QtWidgets.QLineEdit(self.layoutWidget_2)
        self.ntipoA.setObjectName("ntipoA")
        self.verticalLayout_6.addWidget(self.ntipoA)
        self.horizontalLayout_4.addLayout(self.verticalLayout_6)
        self.pantalla.addTab(self.tab_2, "")
        self.tab_3 = QtWidgets.QWidget()
        self.tab_3.setObjectName("tab_3")
        self.bt_actualizar = QtWidgets.QPushButton(self.tab_3)
        self.bt_actualizar.setGeometry(QtCore.QRect(530, 280, 91, 21))
        self.bt_actualizar.setStyleSheet("background-color: rgb(85, 0, 255);\n"
"color: rgb(255, 255, 255);\n"
"font: 75 10pt \"MS Shell Dlg 2\";")
        self.bt_actualizar.setObjectName("bt_actualizar")
        self.codigo_material = QtWidgets.QLineEdit(self.tab_3)
        self.codigo_material.setGeometry(QtCore.QRect(30, 120, 180, 20))
        self.codigo_material.setObjectName("codigo_material")
        self.label_13 = QtWidgets.QLabel(self.tab_3)
        self.label_13.setGeometry(QtCore.QRect(30, 70, 191, 39))
        self.label_13.setObjectName("label_13")
        self.id_buscar = QtWidgets.QPushButton(self.tab_3)
        self.id_buscar.setGeometry(QtCore.QRect(70, 150, 75, 23))
        self.id_buscar.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.id_buscar.setObjectName("id_buscar")
        self.layoutWidget_3 = QtWidgets.QWidget(self.tab_3)
        self.layoutWidget_3.setGeometry(QtCore.QRect(220, 50, 241, 211))
        self.layoutWidget_3.setObjectName("layoutWidget_3")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.layoutWidget_3)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.label_27 = QtWidgets.QLabel(self.layoutWidget_3)
        self.label_27.setObjectName("label_27")
        self.verticalLayout_3.addWidget(self.label_27)
        self.label_25 = QtWidgets.QLabel(self.layoutWidget_3)
        self.label_25.setObjectName("label_25")
        self.verticalLayout_3.addWidget(self.label_25)
        self.label_18 = QtWidgets.QLabel(self.layoutWidget_3)
        self.label_18.setObjectName("label_18")
        self.verticalLayout_3.addWidget(self.label_18)
        self.label_24 = QtWidgets.QLabel(self.layoutWidget_3)
        self.label_24.setObjectName("label_24")
        self.verticalLayout_3.addWidget(self.label_24)
        self.label_26 = QtWidgets.QLabel(self.layoutWidget_3)
        self.label_26.setObjectName("label_26")
        self.verticalLayout_3.addWidget(self.label_26)
        self.horizontalLayout_2.addLayout(self.verticalLayout_3)
        self.verticalLayout_4 = QtWidgets.QVBoxLayout()
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.codigo_actualizar = QtWidgets.QLineEdit(self.layoutWidget_3)
        self.codigo_actualizar.setObjectName("codigo_actualizar")
        self.verticalLayout_4.addWidget(self.codigo_actualizar)
        self.autor_actualizar = QtWidgets.QLineEdit(self.layoutWidget_3)
        self.autor_actualizar.setObjectName("autor_actualizar")
        self.verticalLayout_4.addWidget(self.autor_actualizar)
        self.titulo_actualizar = QtWidgets.QLineEdit(self.layoutWidget_3)
        self.titulo_actualizar.setObjectName("titulo_actualizar")
        self.verticalLayout_4.addWidget(self.titulo_actualizar)
        self.anio_actualizar = QtWidgets.QLineEdit(self.layoutWidget_3)
        self.anio_actualizar.setObjectName("anio_actualizar")
        self.verticalLayout_4.addWidget(self.anio_actualizar)
        self.editorial_actualizar = QtWidgets.QLineEdit(self.layoutWidget_3)
        self.editorial_actualizar.setObjectName("editorial_actualizar")
        self.verticalLayout_4.addWidget(self.editorial_actualizar)
        self.horizontalLayout_2.addLayout(self.verticalLayout_4)
        self.layoutWidget_4 = QtWidgets.QWidget(self.tab_3)
        self.layoutWidget_4.setGeometry(QtCore.QRect(480, 50, 231, 211))
        self.layoutWidget_4.setObjectName("layoutWidget_4")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.layoutWidget_4)
        self.horizontalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout()
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.label_22 = QtWidgets.QLabel(self.layoutWidget_4)
        self.label_22.setObjectName("label_22")
        self.verticalLayout_7.addWidget(self.label_22)
        self.label_20 = QtWidgets.QLabel(self.layoutWidget_4)
        self.label_20.setObjectName("label_20")
        self.verticalLayout_7.addWidget(self.label_20)
        self.label_23 = QtWidgets.QLabel(self.layoutWidget_4)
        self.label_23.setObjectName("label_23")
        self.verticalLayout_7.addWidget(self.label_23)
        self.horizontalLayout_5.addLayout(self.verticalLayout_7)
        self.verticalLayout_8 = QtWidgets.QVBoxLayout()
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.disponible_actualizar = QtWidgets.QLineEdit(self.layoutWidget_4)
        self.disponible_actualizar.setObjectName("disponible_actualizar")
        self.verticalLayout_8.addWidget(self.disponible_actualizar)
        self.cantidad_disponible_actualizar = QtWidgets.QLineEdit(self.layoutWidget_4)
        self.cantidad_disponible_actualizar.setObjectName("cantidad_disponible_actualizar")
        self.verticalLayout_8.addWidget(self.cantidad_disponible_actualizar)
        self.ntipo_actualizar = QtWidgets.QLineEdit(self.layoutWidget_4)
        self.ntipo_actualizar.setObjectName("ntipo_actualizar")
        self.verticalLayout_8.addWidget(self.ntipo_actualizar)
        self.horizontalLayout_5.addLayout(self.verticalLayout_8)
        self.pantalla.addTab(self.tab_3, "")
        self.tab_4 = QtWidgets.QWidget()
        self.tab_4.setObjectName("tab_4")
        self.codigo_borrar = QtWidgets.QLineEdit(self.tab_4)
        self.codigo_borrar.setGeometry(QtCore.QRect(271, 20, 101, 20))
        self.codigo_borrar.setText("")
        self.codigo_borrar.setObjectName("codigo_borrar")
        self.label_12 = QtWidgets.QLabel(self.tab_4)
        self.label_12.setGeometry(QtCore.QRect(220, 20, 45, 16))
        self.label_12.setObjectName("label_12")
        self.borrar_ok = QtWidgets.QPushButton(self.tab_4)
        self.borrar_ok.setGeometry(QtCore.QRect(630, 220, 91, 23))
        self.borrar_ok.setStyleSheet("background-color: rgb(255, 0, 127);")
        self.borrar_ok.setObjectName("borrar_ok")
        self.bt_borrar = QtWidgets.QPushButton(self.tab_4)
        self.bt_borrar.setGeometry(QtCore.QRect(390, 20, 75, 23))
        self.bt_borrar.setStyleSheet("background-color: rgb(85, 0, 255);\n"
"color: rgb(255, 255, 255);\n"
"font: 75 10pt \"MS Shell Dlg 2\";")
        self.bt_borrar.setObjectName("bt_borrar")
        self.tabla_borrar = QtWidgets.QTableWidget(self.tab_4)
        self.tabla_borrar.setGeometry(QtCore.QRect(20, 60, 591, 281))
        self.tabla_borrar.setRowCount(0)
        self.tabla_borrar.setColumnCount(8)
        self.tabla_borrar.setObjectName("tabla_borrar")
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        item.setBackground(QtGui.QColor(255, 0, 191))
        self.tabla_borrar.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        item.setBackground(QtGui.QColor(85, 255, 127))
        self.tabla_borrar.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        item.setBackground(QtGui.QColor(255, 248, 53))
        self.tabla_borrar.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        item.setBackground(QtGui.QColor(0, 170, 127))
        self.tabla_borrar.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        item.setBackground(QtGui.QColor(255, 170, 0))
        self.tabla_borrar.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        item.setBackground(QtGui.QColor(0, 85, 255))
        self.tabla_borrar.setHorizontalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        item.setBackground(QtGui.QColor(163, 83, 26))
        self.tabla_borrar.setHorizontalHeaderItem(6, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        item.setBackground(QtGui.QColor(0, 170, 127))
        self.tabla_borrar.setHorizontalHeaderItem(7, item)
        self.pantalla.addTab(self.tab_4, "")

        self.retranslateUi(Form)
        self.pantalla.setCurrentIndex(3)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "REGISTRO DE MATERIALES"))
        item = self.tabla_materiales.horizontalHeaderItem(0)
        item.setText(_translate("Form", "Codigo"))
        item = self.tabla_materiales.horizontalHeaderItem(1)
        item.setText(_translate("Form", "Autor"))
        item = self.tabla_materiales.horizontalHeaderItem(2)
        item.setText(_translate("Form", "Titulo"))
        item = self.tabla_materiales.horizontalHeaderItem(3)
        item.setText(_translate("Form", "Año"))
        item = self.tabla_materiales.horizontalHeaderItem(4)
        item.setText(_translate("Form", "Editorial"))
        item = self.tabla_materiales.horizontalHeaderItem(5)
        item.setText(_translate("Form", "Disponible"))
        item = self.tabla_materiales.horizontalHeaderItem(6)
        item.setText(_translate("Form", "Cantidad Disponible"))
        item = self.tabla_materiales.horizontalHeaderItem(7)
        item.setText(_translate("Form", "ntipo"))
        self.bt_refrescar.setText(_translate("Form", "REFRESCAR"))
        self.pantalla.setTabText(self.pantalla.indexOf(self.tab_5), _translate("Form", "MATERIALES"))
        self.bt_agregar.setText(_translate("Form", "AGREGAR"))
        self.label_2.setText(_translate("Form", "CODIGO:"))
        self.label_3.setText(_translate("Form", "AUTOR:"))
        self.label_4.setText(_translate("Form", "TITULO:"))
        self.label_5.setText(_translate("Form", "AÑO:"))
        self.label_6.setText(_translate("Form", "EDITORIAL:"))
        self.label_14.setText(_translate("Form", "DISPONIBLE:"))
        self.label_16.setText(_translate("Form", "CANTIDAD_DISPONIBLE:"))
        self.label_17.setText(_translate("Form", "NTIPO:"))
        self.pantalla.setTabText(self.pantalla.indexOf(self.tab_2), _translate("Form", "AGREGAR NUEVOS MATERIALES"))
        self.bt_actualizar.setText(_translate("Form", "ACTUALIZAR"))
        self.label_13.setText(_translate("Form", "INGRESE LA CODIGO DEL MATERIAL"))
        self.id_buscar.setText(_translate("Form", "BUSCAR"))
        self.label_27.setText(_translate("Form", "CODIGO:"))
        self.label_25.setText(_translate("Form", "AUTOR:"))
        self.label_18.setText(_translate("Form", "TITULO:"))
        self.label_24.setText(_translate("Form", "AÑO:"))
        self.label_26.setText(_translate("Form", "EDITORIAL:"))
        self.label_22.setText(_translate("Form", "DISPONIBLE:"))
        self.label_20.setText(_translate("Form", "CANTIDAD_DISPONIBLE:"))
        self.label_23.setText(_translate("Form", "NTIPO:"))
        self.pantalla.setTabText(self.pantalla.indexOf(self.tab_3), _translate("Form", "ACTUALIZAR MATERIALES"))
        self.label_12.setText(_translate("Form", "CODIGO:"))
        self.borrar_ok.setText(_translate("Form", "Consultar"))
        self.bt_borrar.setText(_translate("Form", "BORRAR"))
        item = self.tabla_borrar.horizontalHeaderItem(0)
        item.setText(_translate("Form", "Codigo"))
        item = self.tabla_borrar.horizontalHeaderItem(1)
        item.setText(_translate("Form", "Autor"))
        item = self.tabla_borrar.horizontalHeaderItem(2)
        item.setText(_translate("Form", "Titulo"))
        item = self.tabla_borrar.horizontalHeaderItem(3)
        item.setText(_translate("Form", "Año"))
        item = self.tabla_borrar.horizontalHeaderItem(4)
        item.setText(_translate("Form", "Editorial"))
        item = self.tabla_borrar.horizontalHeaderItem(5)
        item.setText(_translate("Form", "Disponible"))
        item = self.tabla_borrar.horizontalHeaderItem(6)
        item.setText(_translate("Form", "Cantidad Disponible"))
        item = self.tabla_borrar.horizontalHeaderItem(7)
        item.setText(_translate("Form", "ntipo"))
        self.pantalla.setTabText(self.pantalla.indexOf(self.tab_4), _translate("Form", "BORRAR MATERIALES"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())

