# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'GUIPersona.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.setEnabled(True)
        Form.resize(745, 400)
        Form.setMinimumSize(QtCore.QSize(681, 400))
        Form.setStyleSheet("background-color: rgb(223, 223, 223);")
        self.pantalla = QtWidgets.QTabWidget(Form)
        self.pantalla.setEnabled(True)
        self.pantalla.setGeometry(QtCore.QRect(0, 0, 751, 400))
        self.pantalla.setMinimumSize(QtCore.QSize(681, 400))
        self.pantalla.setStyleSheet("background-color: rgb(223, 223, 223);\n"
"selection-color: rgb(0, 0, 0);\n"
"color: rgb(0, 0, 0);\n"
"selection-background-color: rgb(255, 255, 255);\n"
"alternate-background-color: rgb(255, 255, 255);")
        self.pantalla.setObjectName("pantalla")
        self.tab_5 = QtWidgets.QWidget()
        self.tab_5.setObjectName("tab_5")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.tab_5)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.tabla_personas = QtWidgets.QTableWidget(self.tab_5)
        self.tabla_personas.setRowCount(0)
        self.tabla_personas.setColumnCount(10)
        self.tabla_personas.setObjectName("tabla_personas")
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        item.setBackground(QtGui.QColor(255, 0, 191))
        self.tabla_personas.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        item.setBackground(QtGui.QColor(85, 255, 127))
        self.tabla_personas.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        item.setBackground(QtGui.QColor(255, 248, 53))
        self.tabla_personas.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        item.setBackground(QtGui.QColor(0, 170, 127))
        self.tabla_personas.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        item.setBackground(QtGui.QColor(255, 170, 0))
        self.tabla_personas.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        item.setBackground(QtGui.QColor(0, 85, 255))
        self.tabla_personas.setHorizontalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        item.setBackground(QtGui.QColor(163, 83, 26))
        self.tabla_personas.setHorizontalHeaderItem(6, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        item.setBackground(QtGui.QColor(0, 170, 127))
        self.tabla_personas.setHorizontalHeaderItem(7, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        item.setBackground(QtGui.QColor(170, 85, 127))
        self.tabla_personas.setHorizontalHeaderItem(8, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        item.setBackground(QtGui.QColor(0, 170, 255))
        self.tabla_personas.setHorizontalHeaderItem(9, item)
        self.horizontalLayout_3.addWidget(self.tabla_personas)
        self.bt_refrescar = QtWidgets.QPushButton(self.tab_5)
        self.bt_refrescar.setStyleSheet("background-color: rgb(85, 0, 255);\n"
"color: rgb(255, 255, 255);\n"
"font: 75 10pt \"MS Shell Dlg 2\";")
        self.bt_refrescar.setObjectName("bt_refrescar")
        self.horizontalLayout_3.addWidget(self.bt_refrescar)
        self.pantalla.addTab(self.tab_5, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.bt_agregar = QtWidgets.QPushButton(self.tab_2)
        self.bt_agregar.setGeometry(QtCore.QRect(250, 300, 75, 23))
        self.bt_agregar.setStyleSheet("background-color: rgb(85, 0, 255);\n"
"color: rgb(255, 255, 255);\n"
"font: 75 10pt \"MS Shell Dlg 2\";")
        self.bt_agregar.setObjectName("bt_agregar")
        self.layoutWidget = QtWidgets.QWidget(self.tab_2)
        self.layoutWidget.setGeometry(QtCore.QRect(100, 50, 241, 211))
        self.layoutWidget.setObjectName("layoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.layoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label_2 = QtWidgets.QLabel(self.layoutWidget)
        self.label_2.setObjectName("label_2")
        self.verticalLayout_2.addWidget(self.label_2)
        self.label_3 = QtWidgets.QLabel(self.layoutWidget)
        self.label_3.setObjectName("label_3")
        self.verticalLayout_2.addWidget(self.label_3)
        self.label_4 = QtWidgets.QLabel(self.layoutWidget)
        self.label_4.setObjectName("label_4")
        self.verticalLayout_2.addWidget(self.label_4)
        self.label_5 = QtWidgets.QLabel(self.layoutWidget)
        self.label_5.setObjectName("label_5")
        self.verticalLayout_2.addWidget(self.label_5)
        self.label_6 = QtWidgets.QLabel(self.layoutWidget)
        self.label_6.setObjectName("label_6")
        self.verticalLayout_2.addWidget(self.label_6)
        self.horizontalLayout.addLayout(self.verticalLayout_2)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.cedulaA = QtWidgets.QLineEdit(self.layoutWidget)
        self.cedulaA.setObjectName("cedulaA")
        self.verticalLayout.addWidget(self.cedulaA)
        self.nombresA = QtWidgets.QLineEdit(self.layoutWidget)
        self.nombresA.setObjectName("nombresA")
        self.verticalLayout.addWidget(self.nombresA)
        self.apellidosA = QtWidgets.QLineEdit(self.layoutWidget)
        self.apellidosA.setObjectName("apellidosA")
        self.verticalLayout.addWidget(self.apellidosA)
        self.emailA = QtWidgets.QLineEdit(self.layoutWidget)
        self.emailA.setObjectName("emailA")
        self.verticalLayout.addWidget(self.emailA)
        self.telefonoA = QtWidgets.QLineEdit(self.layoutWidget)
        self.telefonoA.setObjectName("telefonoA")
        self.verticalLayout.addWidget(self.telefonoA)
        self.horizontalLayout.addLayout(self.verticalLayout)
        self.layoutWidget_2 = QtWidgets.QWidget(self.tab_2)
        self.layoutWidget_2.setGeometry(QtCore.QRect(410, 50, 231, 211))
        self.layoutWidget_2.setObjectName("layoutWidget_2")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.layoutWidget_2)
        self.horizontalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout()
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.label_14 = QtWidgets.QLabel(self.layoutWidget_2)
        self.label_14.setObjectName("label_14")
        self.verticalLayout_5.addWidget(self.label_14)
        self.label_15 = QtWidgets.QLabel(self.layoutWidget_2)
        self.label_15.setObjectName("label_15")
        self.verticalLayout_5.addWidget(self.label_15)
        self.label_16 = QtWidgets.QLabel(self.layoutWidget_2)
        self.label_16.setObjectName("label_16")
        self.verticalLayout_5.addWidget(self.label_16)
        self.label_17 = QtWidgets.QLabel(self.layoutWidget_2)
        self.label_17.setObjectName("label_17")
        self.verticalLayout_5.addWidget(self.label_17)
        self.label_18 = QtWidgets.QLabel(self.layoutWidget_2)
        self.label_18.setObjectName("label_18")
        self.verticalLayout_5.addWidget(self.label_18)
        self.horizontalLayout_4.addLayout(self.verticalLayout_5)
        self.verticalLayout_6 = QtWidgets.QVBoxLayout()
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.direccionA = QtWidgets.QLineEdit(self.layoutWidget_2)
        self.direccionA.setObjectName("direccionA")
        self.verticalLayout_6.addWidget(self.direccionA)
        self.numero_librosA = QtWidgets.QLineEdit(self.layoutWidget_2)
        self.numero_librosA.setObjectName("numero_librosA")
        self.verticalLayout_6.addWidget(self.numero_librosA)
        self.activoA = QtWidgets.QLineEdit(self.layoutWidget_2)
        self.activoA.setObjectName("activoA")
        self.verticalLayout_6.addWidget(self.activoA)
        self.carreraA = QtWidgets.QLineEdit(self.layoutWidget_2)
        self.carreraA.setObjectName("carreraA")
        self.verticalLayout_6.addWidget(self.carreraA)
        self.rolA = QtWidgets.QLineEdit(self.layoutWidget_2)
        self.rolA.setObjectName("rolA")
        self.verticalLayout_6.addWidget(self.rolA)
        self.horizontalLayout_4.addLayout(self.verticalLayout_6)
        self.pantalla.addTab(self.tab_2, "")
        self.tab_3 = QtWidgets.QWidget()
        self.tab_3.setObjectName("tab_3")
        self.bt_actualizar = QtWidgets.QPushButton(self.tab_3)
        self.bt_actualizar.setGeometry(QtCore.QRect(430, 290, 91, 21))
        self.bt_actualizar.setStyleSheet("background-color: rgb(85, 0, 255);\n"
"color: rgb(255, 255, 255);\n"
"font: 75 10pt \"MS Shell Dlg 2\";")
        self.bt_actualizar.setObjectName("bt_actualizar")
        self.cedula_persona = QtWidgets.QLineEdit(self.tab_3)
        self.cedula_persona.setGeometry(QtCore.QRect(30, 120, 180, 20))
        self.cedula_persona.setObjectName("cedula_persona")
        self.label_13 = QtWidgets.QLabel(self.tab_3)
        self.label_13.setGeometry(QtCore.QRect(30, 70, 191, 39))
        self.label_13.setObjectName("label_13")
        self.id_buscar = QtWidgets.QPushButton(self.tab_3)
        self.id_buscar.setGeometry(QtCore.QRect(70, 150, 75, 23))
        self.id_buscar.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.id_buscar.setObjectName("id_buscar")
        self.layoutWidget_3 = QtWidgets.QWidget(self.tab_3)
        self.layoutWidget_3.setGeometry(QtCore.QRect(230, 50, 241, 211))
        self.layoutWidget_3.setObjectName("layoutWidget_3")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.layoutWidget_3)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.label_7 = QtWidgets.QLabel(self.layoutWidget_3)
        self.label_7.setObjectName("label_7")
        self.verticalLayout_3.addWidget(self.label_7)
        self.label_8 = QtWidgets.QLabel(self.layoutWidget_3)
        self.label_8.setObjectName("label_8")
        self.verticalLayout_3.addWidget(self.label_8)
        self.label_9 = QtWidgets.QLabel(self.layoutWidget_3)
        self.label_9.setObjectName("label_9")
        self.verticalLayout_3.addWidget(self.label_9)
        self.label_10 = QtWidgets.QLabel(self.layoutWidget_3)
        self.label_10.setObjectName("label_10")
        self.verticalLayout_3.addWidget(self.label_10)
        self.label_11 = QtWidgets.QLabel(self.layoutWidget_3)
        self.label_11.setObjectName("label_11")
        self.verticalLayout_3.addWidget(self.label_11)
        self.horizontalLayout_2.addLayout(self.verticalLayout_3)
        self.verticalLayout_4 = QtWidgets.QVBoxLayout()
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.cedula_actualizar = QtWidgets.QLineEdit(self.layoutWidget_3)
        self.cedula_actualizar.setObjectName("cedula_actualizar")
        self.verticalLayout_4.addWidget(self.cedula_actualizar)
        self.nombres_actualizar = QtWidgets.QLineEdit(self.layoutWidget_3)
        self.nombres_actualizar.setObjectName("nombres_actualizar")
        self.verticalLayout_4.addWidget(self.nombres_actualizar)
        self.apellidos_actualizar = QtWidgets.QLineEdit(self.layoutWidget_3)
        self.apellidos_actualizar.setObjectName("apellidos_actualizar")
        self.verticalLayout_4.addWidget(self.apellidos_actualizar)
        self.email_actualizar = QtWidgets.QLineEdit(self.layoutWidget_3)
        self.email_actualizar.setObjectName("email_actualizar")
        self.verticalLayout_4.addWidget(self.email_actualizar)
        self.telefono_actualizar = QtWidgets.QLineEdit(self.layoutWidget_3)
        self.telefono_actualizar.setObjectName("telefono_actualizar")
        self.verticalLayout_4.addWidget(self.telefono_actualizar)
        self.horizontalLayout_2.addLayout(self.verticalLayout_4)
        self.layoutWidget_4 = QtWidgets.QWidget(self.tab_3)
        self.layoutWidget_4.setGeometry(QtCore.QRect(500, 50, 231, 211))
        self.layoutWidget_4.setObjectName("layoutWidget_4")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.layoutWidget_4)
        self.horizontalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout()
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.label_19 = QtWidgets.QLabel(self.layoutWidget_4)
        self.label_19.setObjectName("label_19")
        self.verticalLayout_7.addWidget(self.label_19)
        self.label_20 = QtWidgets.QLabel(self.layoutWidget_4)
        self.label_20.setObjectName("label_20")
        self.verticalLayout_7.addWidget(self.label_20)
        self.label_21 = QtWidgets.QLabel(self.layoutWidget_4)
        self.label_21.setObjectName("label_21")
        self.verticalLayout_7.addWidget(self.label_21)
        self.label_22 = QtWidgets.QLabel(self.layoutWidget_4)
        self.label_22.setObjectName("label_22")
        self.verticalLayout_7.addWidget(self.label_22)
        self.label_23 = QtWidgets.QLabel(self.layoutWidget_4)
        self.label_23.setObjectName("label_23")
        self.verticalLayout_7.addWidget(self.label_23)
        self.horizontalLayout_5.addLayout(self.verticalLayout_7)
        self.verticalLayout_8 = QtWidgets.QVBoxLayout()
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.direccion_actualizar = QtWidgets.QLineEdit(self.layoutWidget_4)
        self.direccion_actualizar.setObjectName("direccion_actualizar")
        self.verticalLayout_8.addWidget(self.direccion_actualizar)
        self.numero_libros_actualizar = QtWidgets.QLineEdit(self.layoutWidget_4)
        self.numero_libros_actualizar.setObjectName("numero_libros_actualizar")
        self.verticalLayout_8.addWidget(self.numero_libros_actualizar)
        self.activo_actualizar = QtWidgets.QLineEdit(self.layoutWidget_4)
        self.activo_actualizar.setObjectName("activo_actualizar")
        self.verticalLayout_8.addWidget(self.activo_actualizar)
        self.carrera_actualizar = QtWidgets.QLineEdit(self.layoutWidget_4)
        self.carrera_actualizar.setObjectName("carrera_actualizar")
        self.verticalLayout_8.addWidget(self.carrera_actualizar)
        self.rol_actualizar = QtWidgets.QLineEdit(self.layoutWidget_4)
        self.rol_actualizar.setObjectName("rol_actualizar")
        self.verticalLayout_8.addWidget(self.rol_actualizar)
        self.horizontalLayout_5.addLayout(self.verticalLayout_8)
        self.pantalla.addTab(self.tab_3, "")
        self.tab_4 = QtWidgets.QWidget()
        self.tab_4.setObjectName("tab_4")
        self.cedula_borrar = QtWidgets.QLineEdit(self.tab_4)
        self.cedula_borrar.setGeometry(QtCore.QRect(241, 20, 101, 20))
        self.cedula_borrar.setText("")
        self.cedula_borrar.setObjectName("cedula_borrar")
        self.label_12 = QtWidgets.QLabel(self.tab_4)
        self.label_12.setGeometry(QtCore.QRect(190, 20, 45, 16))
        self.label_12.setObjectName("label_12")
        self.borrar_ok = QtWidgets.QPushButton(self.tab_4)
        self.borrar_ok.setGeometry(QtCore.QRect(630, 200, 91, 23))
        self.borrar_ok.setStyleSheet("background-color: rgb(255, 0, 127);")
        self.borrar_ok.setObjectName("borrar_ok")
        self.bt_borrar = QtWidgets.QPushButton(self.tab_4)
        self.bt_borrar.setGeometry(QtCore.QRect(360, 20, 75, 23))
        self.bt_borrar.setStyleSheet("background-color: rgb(85, 0, 255);\n"
"color: rgb(255, 255, 255);\n"
"font: 75 10pt \"MS Shell Dlg 2\";")
        self.bt_borrar.setObjectName("bt_borrar")
        self.tabla_borrar = QtWidgets.QTableWidget(self.tab_4)
        self.tabla_borrar.setGeometry(QtCore.QRect(20, 60, 574, 281))
        self.tabla_borrar.setRowCount(0)
        self.tabla_borrar.setColumnCount(10)
        self.tabla_borrar.setObjectName("tabla_borrar")
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        item.setBackground(QtGui.QColor(255, 0, 191))
        self.tabla_borrar.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        item.setBackground(QtGui.QColor(85, 255, 127))
        self.tabla_borrar.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        item.setBackground(QtGui.QColor(255, 248, 53))
        self.tabla_borrar.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        item.setBackground(QtGui.QColor(0, 170, 127))
        self.tabla_borrar.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        item.setBackground(QtGui.QColor(255, 170, 0))
        self.tabla_borrar.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        item.setBackground(QtGui.QColor(0, 85, 255))
        self.tabla_borrar.setHorizontalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        item.setBackground(QtGui.QColor(163, 83, 26))
        self.tabla_borrar.setHorizontalHeaderItem(6, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        item.setBackground(QtGui.QColor(0, 170, 127))
        self.tabla_borrar.setHorizontalHeaderItem(7, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        item.setBackground(QtGui.QColor(170, 85, 127))
        self.tabla_borrar.setHorizontalHeaderItem(8, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        item.setBackground(QtGui.QColor(0, 170, 255))
        self.tabla_borrar.setHorizontalHeaderItem(9, item)
        self.pantalla.addTab(self.tab_4, "")

        self.retranslateUi(Form)
        self.pantalla.setCurrentIndex(1)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "REGISTRO DE PERSONAS"))
        item = self.tabla_personas.horizontalHeaderItem(0)
        item.setText(_translate("Form", "Cedula"))
        item = self.tabla_personas.horizontalHeaderItem(1)
        item.setText(_translate("Form", "Nombres"))
        item = self.tabla_personas.horizontalHeaderItem(2)
        item.setText(_translate("Form", "Apellidos"))
        item = self.tabla_personas.horizontalHeaderItem(3)
        item.setText(_translate("Form", "Email"))
        item = self.tabla_personas.horizontalHeaderItem(4)
        item.setText(_translate("Form", "Telefono"))
        item = self.tabla_personas.horizontalHeaderItem(5)
        item.setText(_translate("Form", "Direccion"))
        item = self.tabla_personas.horizontalHeaderItem(6)
        item.setText(_translate("Form", "Numero_libros"))
        item = self.tabla_personas.horizontalHeaderItem(7)
        item.setText(_translate("Form", "Activo"))
        item = self.tabla_personas.horizontalHeaderItem(8)
        item.setText(_translate("Form", "Carrera"))
        item = self.tabla_personas.horizontalHeaderItem(9)
        item.setText(_translate("Form", "Rol"))
        self.bt_refrescar.setText(_translate("Form", "REFRESCAR"))
        self.pantalla.setTabText(self.pantalla.indexOf(self.tab_5), _translate("Form", "PERSONAS"))
        self.bt_agregar.setText(_translate("Form", "AGREGAR"))
        self.label_2.setText(_translate("Form", "CEDULA:"))
        self.label_3.setText(_translate("Form", "NOMBRES:"))
        self.label_4.setText(_translate("Form", "APELLIDOS:"))
        self.label_5.setText(_translate("Form", "EMAIL:"))
        self.label_6.setText(_translate("Form", "TELEFONO:"))
        self.label_14.setText(_translate("Form", "DIRECCION:"))
        self.label_15.setText(_translate("Form", "NUM_LIBROS:"))
        self.label_16.setText(_translate("Form", "ACTIVO:"))
        self.label_17.setText(_translate("Form", "CARRERA:"))
        self.label_18.setText(_translate("Form", "ROL:"))
        self.pantalla.setTabText(self.pantalla.indexOf(self.tab_2), _translate("Form", "AGREGAR NUEVOS PERSONAS"))
        self.bt_actualizar.setText(_translate("Form", "ACTUALIZAR"))
        self.label_13.setText(_translate("Form", "INGRESE LA CEDULA DE LA PERSONA"))
        self.id_buscar.setText(_translate("Form", "BUSCAR"))
        self.label_7.setText(_translate("Form", "CEDULA:"))
        self.label_8.setText(_translate("Form", "NOMBRES:"))
        self.label_9.setText(_translate("Form", "APELLIDOS:"))
        self.label_10.setText(_translate("Form", "EMAIL:"))
        self.label_11.setText(_translate("Form", "TELEFONO:"))
        self.label_19.setText(_translate("Form", "DIRECCION:"))
        self.label_20.setText(_translate("Form", "NUM_LIBROS:"))
        self.label_21.setText(_translate("Form", "ACTIVO:"))
        self.label_22.setText(_translate("Form", "CARRERA:"))
        self.label_23.setText(_translate("Form", "ROL:"))
        self.pantalla.setTabText(self.pantalla.indexOf(self.tab_3), _translate("Form", "ACTUALIZAR PERSONAS"))
        self.label_12.setText(_translate("Form", "CEDULA:"))
        self.borrar_ok.setText(_translate("Form", "Consultar"))
        self.bt_borrar.setText(_translate("Form", "BORRAR"))
        item = self.tabla_borrar.horizontalHeaderItem(0)
        item.setText(_translate("Form", "Cedula"))
        item = self.tabla_borrar.horizontalHeaderItem(1)
        item.setText(_translate("Form", "Nombres"))
        item = self.tabla_borrar.horizontalHeaderItem(2)
        item.setText(_translate("Form", "Apellidos"))
        item = self.tabla_borrar.horizontalHeaderItem(3)
        item.setText(_translate("Form", "Email"))
        item = self.tabla_borrar.horizontalHeaderItem(4)
        item.setText(_translate("Form", "Telefono"))
        item = self.tabla_borrar.horizontalHeaderItem(5)
        item.setText(_translate("Form", "Direccion"))
        item = self.tabla_borrar.horizontalHeaderItem(6)
        item.setText(_translate("Form", "Numero_libros"))
        item = self.tabla_borrar.horizontalHeaderItem(7)
        item.setText(_translate("Form", "Activo"))
        item = self.tabla_borrar.horizontalHeaderItem(8)
        item.setText(_translate("Form", "Carrera"))
        item = self.tabla_borrar.horizontalHeaderItem(9)
        item.setText(_translate("Form", "Rol"))
        self.pantalla.setTabText(self.pantalla.indexOf(self.tab_4), _translate("Form", "BORRAR PERSONAS"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())

